/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.hragent.controller;import cn.zhuatech.hragent.common.ApiResponse;import cn.zhuatech.hragent.service.EmployeeCaseDecisionReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                             */
@RestController @RequestMapping("/api/enterprise/hragent")public class EmployeeCaseDecisionReleaseController{private final EmployeeCaseDecisionReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                   */
public EmployeeCaseDecisionReleaseController(EmployeeCaseDecisionReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/employee-case-decision-release")public ApiResponse<EmployeeCaseDecisionReleaseService.Assessment>assess(@Valid @RequestBody EmployeeCaseDecisionReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
